default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: miro_development

test:
  <<: *default
  database: miro_test

staging:
  <<: *default
  database: miro_staging


production:
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  adapter: postgresql
  host: db.apple.sinfin.io
  database: miro_production
  encoding: utf8
  collation: cs_CZ.UTF8 
  min_messages: warning
  pool: 20
  timeout: 3000


